version: "3.9"
services:
  client-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - 3000:3000
    volumes:
      - .:/app
      - /app/node_modules
    env_file:
      - .env.local

  client-prod:
    build:
      context: .
      dockerfile: Dockerfile.prod
    ports:
      - 4000:4000
    env_file:
      - .env
      
  pwdb_service:
    image: postgres:16.2
    restart: always
    container_name: pwdb_container
    environment:
      POSTGRES_USER: psqlUser
      POSTGRES_PASSWORD: psqlPassword
      POSTGRES_DB: pwdb
    ports:
      - 5432:5432
    volumes:
      - pwdb_volume:/var/lib/postgresql/data
volumes:
  pwdb_volume:


# docker compose up // run all above builds in development mode
# docker compose down // remove all above builds from docker
# docker compose up specific_service
  # Ex: docker compose up client-dev
# docker save -o apwed.tar apwed_image_name
  # Ex: docker save -o apwed.tar apwed-client-prod
# docker load -i tarName
  # Ex: docker load -i apwed.tar